### ISSUE TITLE
includes/mime.types doesn't exist

### ISSUE THREAD

**Issue by kristbaum** [dolfinus/3DAlloy#2]
Hey,
 I tried to install the extension as described, but couldn't find the mime.types file. Maybe the process has changed. The documentation talks about a new hook, that would be useful for this:

- [Manual:MIME_type_detection](https://www.mediawiki.org/wiki/Manual:MIME_type_detection)
- [Manual:Hooks/MimeMagicInit](https://www.mediawiki.org/wiki/Manual:Hooks/MimeMagicInit)

The hooks should look like this, I just don't know where they should be added:

$mime->addExtraTypes( 'application/json json 3djson 3dj three buff buffjson' );
$mime->addExtraTypes( 'application/obj obj' );
$mime->addExtraTypes( 'application/stl stl stlb' );

$mime->addExtraInfo( 'application/json [TEXT]' );
$mime->addExtraInfo( 'application/obj       [TEXT]' );
$mime->addExtraInfo( 'application/stl       [TEXT]' );

**Comment by dolfinus** [comment]
Hi.

Thank you. I've added MimeHook and released v1.1. Could you try it, please?

**Comment by kristbaum** [comment]
Thanks very much, it works for me now :)

**Comment by dolfinus** [comment]
Great, closing then.
