### ISSUE TITLE
No canvas generated for binary .stl

### ISSUE THREAD

**Issue by merlinmah** [dolfinus/3DAlloy#3]
Hello, 
I've just installed the extension on a MediaWiki 1.37—love the self-contained nature, as opposed to [Extension:3D](https://www.mediawiki.org/wiki/Extension:3D). Uploading an ASCII-encoded .stl generates an interactive view as expected. However, the binary-encoded version of the .stl results in no image, with the MediaWiki file page having no `<canvas>` section. The debug console doesn't appear to have any complaints when loading. [Both .stl files](https://github.com/dolfinus/3DAlloy/files/7573494/Two.STLs.zip) were exported by Fusion 360 and load in the three.js-based [meshlabjs.net](https://meshlabjs.net). Any suggestions for troubleshooting?

**Comment by dolfinus** [comment]
Hi.

Could you try latest extension version?

**Comment by merlinmah** [comment]
Looks fixed to me—works great now. Thank you!
