### ISSUE TITLE
Default scale doesn't always show objects

### ISSUE THREAD

**Issue by squirrelslair** [dolfinus/3DAlloy#7]
Some (all the ones I tried) STL files don't show up with the default scale. Example: 
https://wiki.squirrelslair.ca/index.php?title=Mediawiki_Extension_3DAlloy/default_scale_problem 

Maybe the default scale needs to check the size of the object to set itself to something where that object will fill the canvas? Or, at least, the default should be much smaller - can always zoom in on something if you know it's there and it looks too small, but if it doesn't show at all because it's too big, that's harder to troubleshoot.

**Comment by dolfinus** [comment]
Hello.

Automatic size detection of a model will be a useful feature. However, I don't know how it could be implemented.

**Comment by dolfinus** [comment]
Hello.

I've investigated this issue and found a solution for automatic model rescale.
Also I've fixed center detection for .obj models.

Please try v1.5

**Comment by squirrelslair** [comment]
Tested in v1.5 and both OBJ and STL files now auto scale to a size that fits the viewer and centre in it. Thanks Dolfinus!

**Comment by dolfinus** [comment]
Your welcome!
